apiVersion: apps/v1
kind: Deployment
metadata:
  name: login-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: login-service
  template:
    metadata:
      labels:
        app: login-service
    spec:
      containers:
        - name: login-service
          image: ghcr.io/maengchanho/login-service:latest
          ports:
            - containerPort: 5006
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
      imagePullSecrets:
        - name: ghcr-secrets