apiVersion: apps/v1
kind: Deployment
metadata:
  name: login-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: login-service
  template:
    metadata:
      labels:
        app: login-service
    spec:
      containers:
        - name: login-service
          image: ghcr.io/maengchanho/login-service:latest
          ports:
            - containerPort: 5006
      imagePullSecrets:
        - name: ghcr-secrets